version: '3'

services:
    app: &app
        build:
            context: .
        image: sample_app:1.0.0
        volumes:
            - .:/app:cached
    web:
        <<: *app
        command: rails s -b 0.0.0.0
        ports:
            - "3000:3000"
        links:
            - mysql
    mysql:
        image: mysql:5.6
        environment:
            - MYSQL_USER=app_user
            - MYSQL_PASSWORD=password
        volumes:
            - ./tmp/db:/var/lib/mysql
        ports:
            - "3306:3306"
